apiVersion: apps/v1
kind: Deployment
metadata:
  name: lhcz-demo-crd-front
spec:
  selector:
    matchLabels:
      run: lhcz-demo-crd-front
  template:
    metadata:
      labels:
        run: lhcz-demo-crd-front
    spec:
      containers:
        - name: lhcz-demo-crd-front
          image: registry.cn-qingdao.aliyuncs.com/fuck-k8s/lhcz-demo-crd-front:v4
          ports:
            - name: httpd
              containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: lhcz-demo-crd-front
spec:
  selector:
    run: lhcz-demo-crd-front
#  type: NodePort
  ports:
    - name: httpd
#      nodePort: 30012
      port: 8080
      targetPort: 8082
